package tutorial.loaneligibilty;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String custName;
   private int custAge;
   private double custSalary;

   private java.lang.String status;

   public Customer()
   {
   }

   public java.lang.String getCustName()
   {
      return this.custName;
   }

   public void setCustName(java.lang.String custName)
   {
      this.custName = custName;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public int getCustAge()
   {
      return this.custAge;
   }

   public void setCustAge(int custAge)
   {
      this.custAge = custAge;
   }

   public double getCustSalary()
   {
      return this.custSalary;
   }

   public void setCustSalary(double custSalary)
   {
      this.custSalary = custSalary;
   }

   public Customer(java.lang.String custName, int custAge, double custSalary,
         java.lang.String status)
   {
      this.custName = custName;
      this.custAge = custAge;
      this.custSalary = custSalary;
      this.status = status;
   }
}